Age.create(:age_group => "infant") 
Age.create(:age_group => "toddler") 
Age.create(:age_group => "elementary school") 
Age.create(:age_group => "middle school") 
Age.create(:age_group => "high school") 